Repository cycle/orm, pull requests merged in 2022-11, with the labels that each got.

#378 JTI child entity do not insert embedded relations
  tests/ORM/Functional/Driver/Common/Inheritance/Fixture/ManagerWithCredentials.php
  tests/ORM/Functional/Driver/Common/Inheritance/JTI/Relation/EmbeddedRelationsTest.php
  tests/ORM/Functional/Driver/MySQL/Inheritance/JTI/Relation/EmbeddedRelationsTest.php
  tests/ORM/Functional/Driver/Postgres/Inheritance/JTI/Relation/EmbeddedRelationsTest.php
  tests/ORM/Functional/Driver/SQLServer/Inheritance/JTI/Relation/EmbeddedRelationsTest.php
  tests/ORM/Functional/Driver/SQLite/Inheritance/JTI/Relation/EmbeddedRelationsTest.php
Labels: type:bug, type:test

#379 Adds primary sequence command for JTI
  src/Command/Special/Sequence.php
  src/Transaction/CommandGenerator.php
  tests/ORM/Functional/Driver/Common/Inheritance/Fixture/ManagerWithCredentials.php
  tests/ORM/Functional/Driver/Common/Inheritance/JTI/Relation/EmbeddedRelationsTest.php
  tests/ORM/Functional/Driver/Common/Relation/Embedded/EmbeddedRelationTest.php
  tests/ORM/Functional/Driver/MySQL/Inheritance/JTI/Relation/EmbeddedRelationsTest.php
  tests/ORM/Functional/Driver/Postgres/Inheritance/JTI/Relation/EmbeddedRelationsTest.php
  tests/ORM/Functional/Driver/SQLServer/Inheritance/JTI/Relation/EmbeddedRelationsTest.php
  tests/ORM/Functional/Driver/SQLite/Inheritance/JTI/Relation/EmbeddedRelationsTest.php
Labels: type:bug

#384 Adding support for doctrine/collections 2.x
  composer.json
Labels: type:enhancement, type:feature

#382 [tests] pivoted collection error
  src/Relation/ManyToMany.php
  src/Service/EntityProviderInterface.php
  tests/ORM/Functional/Driver/Common/Integration/Issue322/CaseTest.php
  tests/ORM/Functional/Driver/Common/Integration/Issue322/Entity/Comment.php
  tests/ORM/Functional/Driver/Common/Integration/Issue322/Entity/Post.php
  tests/ORM/Functional/Driver/Common/Integration/Issue322/Entity/PostTag.php
  tests/ORM/Functional/Driver/Common/Integration/Issue322/Entity/Tag.php
  tests/ORM/Functional/Driver/Common/Integration/Issue322/Entity/User.php
  tests/ORM/Functional/Driver/Common/Integration/Issue322/schema.php
  tests/ORM/Functional/Driver/MySQL/Integration/Issue322/CaseTest.php
  tests/ORM/Functional/Driver/Postgres/Integration/Issue322/CaseTest.php
  tests/ORM/Functional/Driver/SQLServer/Integration/Issue322/CaseTest.php
  tests/ORM/Functional/Driver/SQLite/Integration/Issue322/CaseTest.php
Labels: type:bug
